# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

fkey 2 = "merge \"|./test.sh\""
let A0 = 123
leftstring B1 = "outTopic/sensor/humi/2"
let C1 = 2441540
leftstring B2 = "outTopic/sensor/light/0"
let C2 = 2926754
leftstring B3 = "outTopic/sensor/light/1"
let C3 = 2951080
leftstring B4 = "outTopic/sensor/light/1 "
let C4 = 1
leftstring B5 = "outTopic/sensor/pir/3"
let C5 = 1790643
leftstring B6 = "outTopic/sensor/temp/0"
let C6 = 2926606
leftstring B7 = "outTopic/sensor/temp/1"
let C7 = 2951011
leftstring B8 = "outTopic/sensor/temp/2"
let C8 = 2426307
leftstring B9 = "outTopic/sensor/temp/3"
let C9 = 1790676
goto A1 A0
